close #10 add tailwind css and configure files.
ReCoded-Org/capstone-turkey-react-bursapediary pull request #11
Opened 2022-04-03 20:55 UTC by OzerOzturk

2022-04-04 13:21 UTC, maqalaqil requested changes
this is a very big PR @OzerOzturk please write a description for it and for everything you have added to help us Review it.

2022-04-04 17:28 UTC, OzerOzturk commented
I can explain step by step what I did in this pr.

1. eslintrc.json --> I made changes because of the eslint error/warning  I face while rendering. Such as "import/no-default-export". 
2. package.json --> Required packages have been installed to use tailwind css.
3. postcss.config.js --> this file was created while the configuration of tailwind css.
4. App.css --> We don't use app.css  so I deleted default styles.
5. App.jsx --> I deleted default codes and added simple div and h1 to show "hello world" using tailwind css. 
6. store.js --> I made the changes because of the eslint error/warning.
7. index.css --> we have to make some configurations to use tailwind css, this is why I edited it.
8. index.js --> this change is related step 6 (eslint error/warning)
9. tailwind.config.js --> this file was created while the configuration of tailwind css.

2022-04-05 15:43 UTC, Iseluin requested changes
Eslint helps us to write clean and production-level code, so unless we completely have to, let us not touch eslintrc.json file (don't add eslint exceptions). 

If you want, you can delete the whole store and slices since we will configure our own redux store.

All in all, this PR looks good and will be merged after you delete the eslint exception and adjust your code to it.

2022-04-05 15:43 UTC, Iseluin commented on package.json
> +    "prettier": "^2.6.0",
Why was prettier deleted and added again here? Please explain. It might have happened automatically when you added the tailwind library.

2022-04-05 18:56 UTC, OzerOzturk commented on package.json
> +    "prettier": "^2.6.0",
When I added tailwind css, this happened automatically.

2022-04-06 09:13 UTC, merged